128 VnV plan documentation (section 1 and section 3)
wangq131/4G06CapstoneProjectT5 pull request #131
Opened 2023-10-31 22:30 UTC by gaoq20

## Description

PR for VnV plan documentation (section 1 and section 3)

**Issue Link**: 
#128

2023-11-02 23:05 UTC, wangq131 commented
Could you please help remove comments like this 
![Uploading Screen Shot 2023-11-02 at 7.04.18 PM.png…]()

2023-11-02 23:08 UTC, wangq131 commented on docs/VnVPlan/VnVPlan.tex
> +      HTTP & Hypertext Transfer Protocol\\
We might need to add more to this section, I've used `PDF`, `csv`, `txt`

2023-11-02 23:09 UTC, wangq131 commented
I think you forgot to write this section: 
<img width="458" alt="Screen Shot 2023-11-02 at 7 09 03 PM" src="https://github.com/wangq131/4G06CapstoneProjectT5/assets/86222533/fea74f7c-c769-46e3-a2d9-80917a6b8176">
<img width="460" alt="Screen Shot 2023-11-02 at 7 09 15 PM" src="https://github.com/wangq131/4G06CapstoneProjectT5/assets/86222533/17b36d95-0d89-4f12-b0fe-8fac4ed3cc73">

2023-11-02 23:25 UTC, wangq131 commented
I think there is a typo here
<img width="486" alt="Screen Shot 2023-11-02 at 7 24 31 PM" src="https://github.com/wangq131/4G06CapstoneProjectT5/assets/86222533/14fa8d04-e74d-4fa9-835e-5b159310a8de">

2023-11-02 23:28 UTC, wangq131 requested changes
Great work overall except for some small issues, keep it up!

2023-11-02 23:28 UTC, wangq131 commented on docs/VnVPlan/VnVPlan.tex
> +This section outlines the comprehensive strategy for verifying and validating the Course Buddy software, ensuring its alignment with specified requirements and design standards. The plan spans from t
maybe change it to `ensuring it aligns with`

2023-11-02 23:28 UTC, wangq131 commented on docs/VnVPlan/VnVPlan.tex
> +\end{enumerate}
Maybe add a TA/Instructor Review and a Supervisor Review?

2023-11-02 23:28 UTC, wangq131 commented on docs/VnVPlan/VnVPlan.tex
> +        \item 6.2. The Context of the Work
For listing SRS Checklist, I think it is better to link back to the SRS instead of listing all of them out

2023-11-02 23:28 UTC, wangq131 commented on docs/VnVPlan/VnVPlan.tex
> +\end{enumerate}
Similar to above, add TA/Instructor Review and Supervisor Review

2023-11-02 23:28 UTC, wangq131 commented on docs/VnVPlan/VnVPlan.tex
> +\end{itemize}
Please use /textit{} for terminology like `Python`, `Flake8` etc, not just here, for every part you wrote, you should use this for every document to be consistent, thanks!

2023-11-03 03:31 UTC, songc120 approved these changes

2023-11-03 03:40 UTC, wangq131 approved these changes

2023-11-03 03:41 UTC, merged